ftp_server: SERVER
ftp_user: USER
ftp_password: PASSWORD
ftp_passive: 'true'
ftp_outbox_directory: DIRECTORY
ftp_inbox_directory: DIRECTORY
default_route_point_status_id: ID
default_route_point_attended_status_id: ID
default_price_list_id: ID
order_filename: 'ORDER.xml'
ftp_passive: true
server_name: SERVER_NAME
email: EMAIL
mail_server: MAIL_SERVER
mail_user: MAIL_USER
mail_password: MAIL_PASSWORD
smtp_port: 25
server_port: 3000
upload_period: '10'
photo_width_res: '800'
photo_height_res: '600'
message_pull_frequency: '10'
